[colors]
background = '#0e1416'
foreground = '#dee3e5'

cursor_bg = '#83d3e3'
cursor_fg = '#0e1416'
cursor_border = '#83d3e3'

selection_bg = '#004e59'
selection_fg = '#dee3e5'

ansi = ['#0e1416', '#e64c4e', '#76d66e', '#dbcc7b', '#3f96a8', '#70a0aa', '#83d3e3', '#abb2bf']
brights = ['#5c6370', '#e05f66', '#8ce086', '#e8db97', '#8be1f3', '#368887', '#537f92', '#ffffff']
