[colors]
background = '#0e1514'
foreground = '#dde4e2'

cursor_bg = '#81d5ca'
cursor_fg = '#0e1514'
cursor_border = '#81d5ca'

selection_bg = '#005049'
selection_fg = '#dde4e2'

ansi = ['#0e1514', '#e54b53', '#79d66e', '#dbc97b', '#3e9c90', '#6d9f99', '#81d5ca', '#abb2bf']
brights = ['#5c6370', '#e05f6a', '#8fe086', '#e8d997', '#8ae4d8', '#3a876e', '#478282', '#ffffff']
